### ISSUE TITLE
深色主题下，开启插件会导致

### ISSUE THREAD

**Issue by grisbear** [LastKnightCoder/obsidian-antd#1]
![JEI~OS{L`}1{A65D92K8}JJ](https://user-images.githubusercontent.com/74553083/205421915-34051650-0114-43d8-a084-f1f43cce7cb0.png)

**Comment by LastKnightCoder** [comment]
应该是 antd 的样式覆盖了，可以自定义样式解决

```css
body {
  --text-normal: #0e0e0e;
  color: var(--text-normal);
}
body.theme-dark {
  --text-normal: rgba(242, 248, 253, 0.9);
}
```
