### ISSUE TITLE
没有达到预期效果

### ISSUE THREAD

**Issue by grisbear** [LastKnightCoder/obsidian-antd#2]
![~OB0OCBUDO L52M7 ICA 2](https://user-images.githubusercontent.com/74553083/205424657-311057be-8cc5-497e-8c68-2d6796914196.png)

javascript 点击 并没有切换

深夜模式下，有些字没有适配。

**Comment by LastKnightCoder** [comment]
这是我自己的一些适配

```css
.ant-tabs {
  color: var(--text-normal) !important;
}

.ant-progress-text {
  color: var(--text-normal) !important;
}

.ant-btn-primary:not([disabled]) {
  background-color: #1890ff !important;
}
```

如果有问题可以审查元素然后修改，Antd 的样式是暴露到全局的，会影响已有样式，一般是发现什么问题就修复什么问题。
